name: CD - Deploy to EC2

on:
   workflow_run:
    workflows: ["CI - Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Pull docker image
      run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth-microservices:latest

    - name: Delete Old docker container
      run: sudo docker rm -f auth-microservices-container || true

    - name: Run Docker Container
      run: |
            docker run -d -p 5002:5002 --name auth-microservices-container \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e DATABASE_APITABLE_URL="${{ secrets.DATABASE_APITABLE_URL }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e EMAIL_USERNAME="${{ secrets.EMAIL_USERNAME }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e NODE_ENV="development" \
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-microservices:latest
